[0m16:14:23.766552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172E0A61B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172E205B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172E207860>]}


============================== 16:14:23.810046 | d15b9d34-ce53-46d8-9879-3a5ec341a04b ==============================
[0m16:14:23.810046 [info ] [MainThread]: Running with dbt=1.7.14
[0m16:14:23.814258 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:14:58.194109 [debug] [MainThread]: Starter project path: c:\Users\cmotte\DVF_data\.venv\Lib\site-packages\dbt\include\starter_project
[0m16:14:58.293239 [info ] [MainThread]: 
Your new dbt project "dvf_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:14:58.298849 [info ] [MainThread]: Setting up your profile.
[0m16:16:13.723103 [debug] [MainThread]: Command `dbt init` succeeded at 16:16:13.723103 after 110.39 seconds
[0m16:16:13.725110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172B438C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172E06A870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002172E0A61B0>]}
[0m16:16:13.727071 [debug] [MainThread]: Flushing usage events
[0m16:16:13.743736 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m04:46:56.480620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC63A0FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC63A2390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC63A0C20>]}


============================== 04:46:56.495858 | f90f3bed-81b3-41e6-a189-e38853c51b2a ==============================
[0m04:46:56.495858 [info ] [MainThread]: Running with dbt=1.7.10
[0m04:46:56.498879 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:46:56.500780 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt-dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m04:46:56.506043 [debug] [MainThread]: Command `dbt test` failed at 04:46:56.506043 after 0.21 seconds
[0m04:46:56.507045 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC62A1C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC62A23C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017FC5D64E30>]}
[0m04:46:56.508904 [debug] [MainThread]: Flushing usage events
[0m04:46:56.523598 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m13:20:28.300895 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC881A26F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC881A0B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC881A17C0>]}


============================== 13:20:28.306268 | 4bd130af-4822-426e-974e-5dc3c75155d4 ==============================
[0m13:20:28.306268 [info ] [MainThread]: Running with dbt=1.7.10
[0m13:20:28.313779 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt test', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:20:28.313779 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt-dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:20:28.320678 [debug] [MainThread]: Command `dbt test` failed at 13:20:28.320678 after 0.19 seconds
[0m13:20:28.320678 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC87FADC40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC87F240E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002DC87FC2570>]}
[0m13:20:28.327042 [debug] [MainThread]: Flushing usage events
[0m13:20:28.343611 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
[0m10:45:52.417203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF2A97A750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF2A97AB40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF2A97A960>]}


============================== 10:45:52.448593 | a21d11f9-378f-4341-b151-f564a6ed1a04 ==============================
[0m10:45:52.448593 [info ] [MainThread]: Running with dbt=1.7.10
[0m10:45:52.448593 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\cmotte\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:45:52.453579 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\cmotte\dbt_for_dvf\dbt-dvf\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:45:52.457262 [debug] [MainThread]: Command `dbt run` failed at 10:45:52.457262 after 0.34 seconds
[0m10:45:52.457262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF26B25820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF2A697FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EF2A9A3E90>]}
[0m10:45:52.462347 [debug] [MainThread]: Flushing usage events
[0m10:45:52.488390 [debug] [MainThread]: Error sending anonymous usage statistics. Disabling tracking for this execution. If you wish to permanently disable tracking, see: https://docs.getdbt.com/reference/global-configs#send-anonymous-usage-stats.
